LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE components IS

	COMPONENT register16bits
		PORT (D                  : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
				Clock, Resetn, Rin : IN STD_LOGIC;
				Q                  : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
	END COMPONENT;	
	
	COMPONENT fullAdder 
		PORT (cin:  IN STD_LOGIC;
				a, b: IN STD_LOGIC;
				S:    OUT STD_LOGIC;
				cout: OUT STD_LOGIC);
	
	END COMPONENT;
	
	COMPONENT rippleCarry
		PORT (cin            : IN STD_LOGIC ;
				a,b            : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
				S              : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
				cout, overflow : OUT STD_LOGIC );
	END COMPONENT;
	
	COMPONENT Forward_Unit
		PORT (EX_MEM_RegWrite: IN STD_LOGIC;
				MEM_WB_RegWrite: IN STD_LOGIC;
				EX_MEM_Rd: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
				MEM_WB_Rd: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
				ID_EX_Rs: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
				ID_EX_Rt: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
				Forward_A: OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
				Forward_B: OUT STD_LOGIC_VECTOR(1 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT mux2to1
		PORT (a,b : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
				s   : IN STD_LOGIC;
				y   : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT mux3to1
		PORT (a,b,c : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
			s     : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
			y     : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT Control
		PORT(Opcode: IN STD_LOGIC_VECTOR(2 DOWNTO 0); 
			  ID_Flush: OUT STD_LOGIC;
			  Control_Signals: OUT STD_LOGIC_VECTOR(7 DOWNTO 0));	  
	END COMPONENT;
	
	COMPONENT shiftLeft
		PORT (DataIn  : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
				DataOut : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT signalExtend
		PORT (DataIn  : IN STD_LOGIC_VECTOR(4 DOWNTO 0);
				DataOut : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT Reg_ID_EX 
		PORT(
		Clk: IN STD_LOGIC;
		D : IN STD_LOGIC_VECTOR(83 DOWNTO 0);
		Q : OUT STD_LOGIC_VECTOR(83 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT Reg_EX_MEM
		PORT(	
			Clk : IN STD_LOGIC;
			D   : IN  STD_LOGIC_VECTOR(39 DOWNTO 0);
			Q   : OUT STD_LOGIC_VECTOR(39 DOWNTO 0));
	END COMPONENT;
	
	COMPONENT Reg_MEM_WB
		PORT(	
			Clk : IN STD_LOGIC;
			D   : IN  STD_LOGIC_VECTOR(37 DOWNTO 0);
			Q   : OUT STD_LOGIC_VECTOR(37 DOWNTO 0));
	END COMPONENT;
	
END components;
